language: node_js
node_js:
  - "4"

env:
  global:
   - secure: "zwaj6GzKtRpNfmaKZ9qxuBHVBSrBtQU8WDPpbIj95TM6JAx9N9OBEFqJ1ukXDDkZOO5TegTdKhgIiuBarwkh5+yquUPozGoUP+B2R3n3QA92rPq01ZuCRR7paJY70WUREip1J4VLARBK6hIxS0j63jX9lrUfDNMy8GdRRI1GZ56iG57DalLhOSzeLx+w0lVMvFpVQnPB1ctDJDR/zVm+31HJ47+C6YgjZdA1/pL3ajPXQmWLYdlfqi/Ydh8NFzE1CSAXgkuyGzfDrnXae2VP+/0wXRUxp2R7b6OlH/9OEWvnVYRGZBbtYu8WVX5YGmcBdfAcLakwdg8Tysrdsu+O16ts0Y6u/43ZcRBGUOzc2ZftixEPWfPXRIvhwmkLEhmOal5erochuRKxehZ9XhNC0YlYCm7kfwbuigqFGE66fu0VGF/w/tbfL6RwraawAKYE7qnP8B+T2SGhrNKBTB2EGIAewuarbOZHfyLylY9gWhL74Ws6nWHHlRr+xvTwcv5aGQHDJ8KChky+amn/qQFWyVKTDtoz6pU/tFXUWULa+TSdyV5V63OuBTGUwyIil/CtKdoTx5bbWI2/Qvoh/bIY7uje49VFrKkoUJkvdG7mEgX2U8u7JYCQ9xwttqLzjBum0XultVgiB6zINvHjlUQHpTULCHn4O4FgMhHqFIKrKHg="
   - secure: "OWaV+iHKyMkrJtvgedGm2nk4HmhfvAXEtIqWFgRLWBVm7eC0pJRnLoGUFNLh6MYdWuVrqR3h+cnBdGB4SDmPsZJFUDTNzlvuZGxZJBOIqZx4Shue9Cu1+aCHb6g1Ea8Qf5ioBZaahUAOJbFcsB9ViNEjxlbOR2pOKUb+mDYMIkCDWLrR+mvb6toPpKEu+u+eDGAY78Ek13sib/gR3uSHFygSQOhXfIkZ4tel0/Eoy4WWyZ1Ds5VC1uKPNrSS1LfBeI2JaOmLt7Nv9DnQIB1gKIV7pCzaJWAn8gQoKU5I6/YJiT57JXMjcU7s+6zyOMwGGMxXJy/XlnEh8cTBdHvAu8Vszg2eHP+e7WKUTQXIOvj89tJWjyLdx/q0o7Q4KkfJ7GvMFa2Zq5EoyPi0Hc6tCh0Pffx46p4DzPPDsQsy90XZVBiKVAI3eFdpbPGMi3Sye70JbA9aLpnKd5Vqoyoy6pzRMBznHo+GXULADAZbMKK+d5cEBOVGBQVniTXA3OPtv/OgQj1FhKnB6X12RwxRUMkwitVnrxEjRU7hKy/FEax7Bm0NPrpJaFq8uY0IEAk1O3HyAyEuQGk6+QNj6ETqYg5cA77zgsUN0NmwMwUjkp/drA5uiDPGN0uhdGRjVL+i0fklPozcAObgmD8wsBExwsVkIf6ea++QUXPGltwbHzo="

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - git config --global user.email "aschan.johan@gmail.com"
  - git config --global user.name "johanaschan"
  - git remote set-url origin "https://${GH_TOKEN}@github.com/johanaschan/queue-ticket-web"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ng github-pages:deploy