language: node_js

node_js:
  - '4'

notifications:
  slack:
    secure: Zg3TANonRFYnSTy+liZ3omNaZ3ecI1a4ffUBn4njZ6oKxXrmqG7BkpVlrrM17tWSJwzOmi03KKcoJWMHl8txyQdtmBNyNaKdKnsbi19hxDsUPoC6fMvP4RryQesbla+SzVbrdFQAlD+oeyFSjVuHBnEU6hXKaEXrzNgeE85K0EcX3ZBaxR1v/egJi3tjxtkfVJhb3aOmDp4ZskU7VKbuHkEwv4GCMmHejMTG13fBn13WkjFz/AlnjOTX5wBr80Kyhvt/RO2Ojq3YWVYF9ODRpWB1vwUkb6nWxATJcEdslqWmiiisuHH6FAlCYCYySrch1CJLE/oT3ZPm4uJ/6nRNqOFZMt3jqoa39AIldBRz5hJC36UKYCpFir58cN6pBCleshXHJCqdLAmzKHhKo4cFsiRtkazSmZ5P9tvZCOCgICCcN4ZIL4NxWK2cmd9wZq2UT6AiFZSiKJ/8SZLvBcxwQA2TGvWIV/65MqAIirt3t3ldSTJzlCluWJhkwY41W3qN9tlCmg0lyAJS1Vgs9n6q3fBqVOiUqNAC/tFE5R2+KQ8Vdgh0R5yFGaAyNtvH9f/x6YOmS9zGOrsSEeyxlV2uaDxrryD4IrLLe2WaAEAgIcjxQXHfVsoxAQ6NuV6hcMz1ZP51AYYZNyxK0274mvr/EIEf3IBz501RPXTnJtsGs94=

before_install:
  - openssl aes-256-cbc -K $encrypted_d81357c35ba2_key -iv $encrypted_d81357c35ba2_iv -in deploy_rsa.enc -out deploy_rsa -d
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis"
  - git remote set-url origin "git@github.com:johanaschan/queue-ticket-web.git"
  - git pull origin gh-pages:gh-pages
  - git checkout .
  - ng github-pages:deploy
